---
- name: Initial setup for com2 - create clusteradmin user
  hosts: compute_new
  gather_facts: yes
  become: yes

  tasks:
    - name: Create clusteradmin user
      user:
        name: clusteradmin
        state: present
        groups: wheel
        append: yes
        create_home: yes

    - name: Set password for clusteradmin
      user:
        name: clusteradmin
        password: "{{ 'clusteradmin123' | password_hash('sha512') }}"

    - name: Configure sudo for clusteradmin
      copy:
        content: "clusteradmin ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/clusteradmin
        mode: 0440

    - name: Create .ssh directory for clusteradmin
      file:
        path: /home/clusteradmin/.ssh
        state: directory
        owner: clusteradmin
        group: clusteradmin
        mode: 0700

    - name: Copy SSH public key to clusteradmin using shell
      shell: |
        cat /tmp/ssh_key.pub >> /home/clusteradmin/.ssh/authorized_keys
        chown clusteradmin:clusteradmin /home/clusteradmin/.ssh/authorized_keys
        chmod 600 /home/clusteradmin/.ssh/authorized_keys

    - name: Configure /etc/hosts for cluster
      blockinfile:
        path: /etc/hosts
        block: |
          10.106.0.5 head
          10.106.0.4 com1
          {{ ansible_default_ipv4.address }} com2
        marker: "# {mark} ANSIBLE MANAGED BLOCK - CLUSTER NODES"

    - name: Set hostname to com2
      hostname:
        name: com2

- name: Verify clusteradmin setup on com2
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Test SSH as clusteradmin to com2
      command: ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key clusteradmin@{{ groups['compute_new'][0] }} "echo 'com2 accessible as clusteradmin'"
      register: test_result
      changed_when: false

    - name: Display test result
      debug:
        msg: "{{ test_result.stdout }}"
