name: Deploy Compute Node

on:
  push:
    branches: [ main ]

env:
  TERRAFORM_VERSION: 1.5.7

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass jq

    - name: Clean up duplicate Terraform files
      run: |
        cd terraform
        if [ -f provider.tf ]; then
          rm -f provider.tf
        fi

    - name: Generate SSH key pair
      run: |
        mkdir -p /tmp/.ssh
        ssh-keygen -t rsa -b 4096 -f /tmp/ssh_key -N "" -C "github-actions-cluster"
        echo "=== Public Key ==="
        cat /tmp/ssh_key.pub

    - name: Create terraform.tfvars from secrets
      run: |
        echo 'do_token = "${{ secrets.DIGITALOCEAN_TOKEN }}"' > terraform/terraform.tfvars
        echo 'region = "lon1"' >> terraform/terraform.tfvars
        echo 'cluster_name = "student-cluster"' >> terraform/terraform.tfvars
        echo 'com2_size = "s-2vcpu-4gb"' >> terraform/terraform.tfvars
        echo 'image = "rockylinux-9-x64"' >> terraform/terraform.tfvars
        echo 'private_key_path = "/tmp/ssh_key"' >> terraform/terraform.tfvars
        echo 'tags = ["github-actions", "hpc-cluster", "automated"]' >> terraform/terraform.tfvars
        echo 'existing_droplet_names = ["head", "com1"]' >> terraform/terraform.tfvars

    - name: Setup SSH key for Terraform
      run: |
        cp /tmp/ssh_key.pub terraform/ssh_key.pub
        chmod 600 /tmp/ssh_key

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform plan
        timeout 180s terraform apply -auto-approve

    - name: Wait for com2 to be ready
      run: |
        sleep 30

    - name: Extract and display IP addresses
      run: |
        cd terraform
        echo "=== Extracting IP addresses ==="
        
        # Get the IP directly from Terraform output
        COM2_IP=$(terraform output -raw com2_ip 2>/dev/null || echo "")
        
        if [ -z "$COM2_IP" ]; then
          echo "Terraform output failed, trying to extract from state"
          terraform show -json > tfstate.json
          COM2_IP=$(jq -r '.values.root_module.resources[] | select(.name=="com2") | .values.ipv4_address' tfstate.json 2>/dev/null || echo "159.65.17.107")
        fi
        
        echo "Com2 IP: $COM2_IP"
        echo "COM2_IP=$COM2_IP" >> $GITHUB_ENV

    - name: Create clusteradmin user on com2
      run: |
        echo "Creating clusteradmin user on com2 at $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "useradd -m -s /bin/bash clusteradmin"

    - name: Setup sudo access for clusteradmin
      run: |
        echo "Setting up sudo access for clusteradmin on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "echo 'clusteradmin ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/clusteradmin"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "chmod 440 /etc/sudoers.d/clusteradmin"

    - name: Add SSH key to clusteradmin
      run: |
        echo "Adding SSH key to clusteradmin on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "mkdir -p /home/clusteradmin/.ssh"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBWXU12cxnyWt+hhOJJfrk+YwsEYFTt5uNFqjUzsUKy2 clusteradmin@head' > /home/clusteradmin/.ssh/authorized_keys"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$CO2_IP "chmod 700 /home/clusteradmin/.ssh"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "chmod 600 /home/clusteradmin/.ssh/authorized_keys"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "chown -R clusteradmin:clusteradmin /home/clusteradmin/.ssh"

    - name: Install NFS client on com2
      run: |
        echo "Installing NFS client on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "dnf install -y nfs-utils"

    - name: Setup NFS mount on com2
      run: |
        echo "Setting up NFS mount on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "mkdir -p /home/clusteradmin/shared"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "chown clusteradmin:clusteradmin /home/clusteradmin/shared"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "echo '157.245.35.46:/home/clusteradmin/shared /home/clusteradmin/shared nfs defaults 0 0' >> /etc/fstab"

    - name: Verify clusteradmin user
      run: |
        echo "Verifying clusteradmin user on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "getent passwd clusteradmin && echo 'User created successfully'"

    - name: Verify SSH key setup
      run: |
        echo "Verifying SSH key setup on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "ls -la /home/clusteradmin/.ssh/ && echo 'SSH directory created'"

    - name: Verify sudo access
      run: |
        echo "Verifying sudo access on $COM2_IP"
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key root@$COM2_IP "sudo -U clusteradmin -l && echo 'Sudo access verified'"

    - name: Display completion message
      run: |
        echo "=========================================="
        echo "✅ DEPLOYMENT COMPLETE"
        echo "=========================================="
        echo "com2 node: $COM2_IP"
        echo "User: clusteradmin"
        echo "SSH Key: Added from head node"
        echo "NFS: Configured (add to fstab)"
        echo ""
        echo "To connect: ssh clusteradmin@$COM2_IP"
        echo "To mount NFS: mount /home/clusteradmin/shared"
        echo "=========================================="
